# Generated by Django 3.2.4 on 2021-07-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20210707_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
